import { createApp } from 'vue';
import App from './App';
import router from './router';
import store from './store';
import 'normalize.css';
import registerAntdUIs from './antd-ui';
import '@/styles/index.less';
import './permission';
const app = createApp(App);
registerAntdUIs(app);
app.use(router).use(store).mount('#app');
